### ISSUE TITLE
Asustor web portal setup is so easy

### ISSUE THREAD

**Issue by 007revad** [wallacebrf/Synology-SMART-test-scheduler#15]
![image](https://github.com/user-attachments/assets/c909663b-b1d1-4f25-84e7-ab4ec8ea1cc5)

I kept the default PHP 7.2 and Apache.

http://192.168.20.190/synology_smart/smart_scheduler_config.php
![image](https://github.com/user-attachments/assets/dbcbd093-0efc-4093-91c2-d966745f376b)

**Comment by wallacebrf** [comment]
awesome, yea, synology web station takes a lot of steps to setup right, but i was able to re-create the web station on my spare DS920

**Comment by 007revad** [comment]
What's with the default time of 08:50:52 PM ? :o)

Maybe something like 08:00:00 PM would make it easier for people to edit?

**Comment by wallacebrf** [comment]
that is because the file was created/executed at that time. you can then override it

**Comment by 007revad** [comment]
So it's the last time I ran the bash script.

**Comment by wallacebrf** [comment]
correct

**Comment by 007revad** [comment]
The tables are empty because I didn't notice that you're setting the `$script_location="/volume1/web/synology_smart";` in the php file (and my Asustor's shared folder is Web instead of web.

It would be better to put the common user editable settings in a config file so that:  
1. Users only need to set the variables in 1 place.
2. Users don't touch the .sh or .php files.

I would put the following in the config file: 
- script_location
- email_address
- from_email_address

This would also mean people don't need to edit the .sh and .php files each time the script is updated.

**Comment by wallacebrf** [comment]
can you provide a basic write-up on configuring the Asustor's web site?

i will add my instructions on configuring synology web-station to the read me sometime tomorrow

**Comment by 007revad** [comment]
Did you see my config file suggestion in my previous comment?

Here's the steps for configuring an Asustor's web site: 
```
1. In ADM click on Web Center > Implementation.
2. Check that PHP is installed and showing "Status: Active".
3. Check either Apache or Nginx is installed and showing "Status: Active".
4. Click on the "Web Server" tab.
5. Check "Web server implementation" is set to Apache or Nginx.
6. Tick "Enable Web server port" and/or "Enable secure Web server port".
7. Change the "Web server port" and/or "secure Web server port" to your desired ports, or leave them on the defaults.
8. Check "PHP implementation" is set to the installed PHP version.
9. Click on the "Virtual Host" tab.
10. Click Add.
11. Give it a unique Host name (e.g. "smart" will do).
12. Select the Protocol you prefer (HTTP or HTTPS).
13. If you set a web server port in step 7 make sure that "Port number" matches.
14. Click Browse and browse to "Web > synology_smart".
15. Click OK.

You can now access the Synology-SMART-scheduler webui on either:
- https://<ip-address>/synology_smart/smart_scheduler_config.php
- http://<ip-address>/synology_smart/smart_scheduler_config.php

Note: Replace <ip-address> with your Asustor's IP Address or Hostname.
```

**Comment by wallacebrf** [comment]
yes, i saw the comment on the config file. i will work on that tomorrow. 

when i add the instructions to the read-me for the synology web-station i will also add the instructions you just posted above so we have better instructions for more users. 

tomorrow i will also add the instructions on how to directly edit the config file if someone does not wish to use a web-interface

**Comment by 007revad** [comment]
You should also explain to run manual short and long tests (for those who may not wish to use a web-interface).

**Comment by wallacebrf** [comment]
good idea, i will do that too.

**Comment by wallacebrf** [comment]
read me updated:

sections added
6.6.) Synology Web-Station setup
6.7.) Asustor web portal setup
6.8.) Configuration of required user level settings
6.8.1.) Configuration through PHP Web-Interface
6.8.2.) Configuration without using a web-interface
