### ISSUE TITLE
add reload button to web-interface that does not resubmit the form data

### ISSUE THREAD

**Issue by wallacebrf** [wallacebrf/Synology-SMART-test-scheduler#21]
possible solutions:

https://stackoverflow.com/questions/570015/how-do-i-reload-a-page-without-a-postdata-warning-in-javascript
https://stackoverflow.com/questions/6661175/how-can-i-refresh-a-webpage-without-the-browser-asking-if-i-want-to-resend-again
https://stackoverflow.com/questions/8000798/reload-refresh-page-in-browser-without-re-submitting-form

this one looks the most promising
https://stackoverflow.com/questions/6320113/how-to-prevent-form-resubmission-when-page-is-refreshed-f5-ctrlr

**Comment by wallacebrf** [comment]
added code to the web page to check every form submission to ensure it was a legit user submission and not ones that was previously submitted. this will prevent issues like tests starting or cancelling when refreshing the page and seeing this window

![image](https://github.com/user-attachments/assets/c5e2c135-42e0-46dd-bc54-ae3890f4143b)

**Comment by 007revad** [comment]
I'm still getting the same issue with the latest version. This is in chrome.

![image](https://github.com/user-attachments/assets/df28bd04-5677-4640-9919-5f5a47c8535d)

It occurs if I try to refresh the webui after all of the following steps.
- I selected to manually run short tests.
- Ran the script. 
- Wait until tests have finished.
- Run the script.

**Comment by wallacebrf** [comment]
Yes I cannot make chrome NOT show that warning what I did was make the PHP script ignores the form data submission from a screen refresh. It will only accept data when it is actually submitted from a valid form submission using a random number generator and session variables 

I tested it after making manual test and test cancellations. The file is created and when the script executes and deletes the file, after refreshing the page the manual start and cancel filea we're not created.

**Comment by 007revad** [comment]
Apparently, for Chrome, you need to Post/Redirect/Get (PRG) instead of just Post.
https://www.tutorialspoint.com/php/php_post_redirect_get_prg.htm

**Comment by wallacebrf** [comment]
Ok, thanks for the details I did not test on chrome. I will update the PHP code to use the PRG method. 


i just tested on chrome and edge. while they do pop up that message about form data being resubmitted i am able to confirm that the code i have does properly PREVENT the php script from executing the incorrectly submitted form data. the form data is only processed when it is submitted through a valid form submission. 

with that said, if the PRG method will get rid of the pop up warning then it will be worth it. 

i will also then have to update a lot of my other script web-pages with the same code.
