### ISSUE TITLE
I'm bored :(

### ISSUE THREAD

**Issue by 007revad** [wallacebrf/Synology-SMART-test-scheduler#24]
Do you have anything you need done?

**Comment by wallacebrf** [comment]
lol,

at the moment no. this week i have been too busy with work to work more on this project. i will be working more on the project this weekend where i hope to finish the other two outstanding issues, and then i was planning to make a post on reddit letting people know in the synology section about the script.

**Comment by wallacebrf** [comment]
the only other thing i really have on my to-do list is to add the USB disk support and the synology slot location to my SMART to Influxdb logger script, but that is a fairly minimal thing.

**Comment by wallacebrf** [comment]
you can look at the issue i just added about ensuring no scrubbing is active before allowing a SMART scan to start. i was going to use the code already in my scrubbing status script to perform the check. you could take a stab at the change if you desire.

**Comment by wallacebrf** [comment]
Let me know if you are interested otherwise I was going to work on that and some of the other issues this weekend

**Comment by 007revad** [comment]
Looking at your Synology_Data_Scrub_Status script it looks like you have the code you need.

I assume you'll check if RAID is resyncing and if a SMART test is active.

**Comment by wallacebrf** [comment]
Correct I am simply going to make functions to check if BTRFS is active and to see if raid scrubbing is active. Like you said I do already have the code I just need to roll the code into the smart scheduler

**Comment by wallacebrf** [comment]
figured the project that guy on reddit was asking for on the BTRFS snapshots might give you something to work on :)

**Comment by 007revad** [comment]
It's proving to be a little trickier than I thought... but I like a challenge.
