### ISSUE TITLE
Estimated test durations

### ISSUE THREAD

**Issue by 007revad** [wallacebrf/Synology-SMART-test-scheduler#29]
Are you aware that the "Short Test Duration (est)" column is blank?

Also the "Extended Test Duration (est)" has a space after the "(" but only on a Synology.

Synology
![image](https://github.com/user-attachments/assets/aca47529-fcb3-4b53-bb8d-f7a2bcfabe73)

Asustor
![image](https://github.com/user-attachments/assets/dfa7f473-9a38-4948-bff6-29756a9288be)

**Comment by wallacebrf** [comment]
make sure you have the latest .php and .sh file, and make sure the .sh file has executed, both are needed as i do not have that problem

![image](https://github.com/user-attachments/assets/db92b6d4-88e2-47ff-afd6-9628e4c80eef)

**Comment by wallacebrf** [comment]
that space after the "(" is direct;y from the output of smartctl. i am not modifying it

**Comment by wallacebrf** [comment]
I can update the .sh file so it perform a search and replace of spaces so they are not there. I would also remove the brackets, this far I just took the raw output from smartctl.

**Comment by 007revad** [comment]
synology_SMART_control.sh is v1.7 from 5 hours ago. smart_scheduler_config.php is from 4.5 hours ago.

After selecting "Manual short test" for all 4 drives in the Asustor, and running synology_SMART_control.sh it now looks like this: 
![image](https://github.com/user-attachments/assets/b106b71c-c642-4437-ab79-d8ff51674a40)

But once the smart tests had finished, and I ran the script again, it's now showing estimated extended and shot test times.
![image](https://github.com/user-attachments/assets/8a69e2fe-0205-4fa4-86ca-6dcce584f95a)

**Comment by wallacebrf** [comment]
Yes while the test is running I do NOT show the estimated times as I did not want to risk people thinking that is the estimated time REMAINING.

**Comment by wallacebrf** [comment]
I will close this issue since they are displaying correctly when the tests are not active
