### ISSUE TITLE
Logo on webui

### ISSUE THREAD

**Issue by 007revad** [wallacebrf/Synology-SMART-test-scheduler#30]
I'm trying to put a little 64x64 logo on the webui like:
![image](https://github.com/user-attachments/assets/3b6c6df5-a7e4-4dbe-9ff8-b952a0e5ac27)

<br>

This is as far as I've got:
```
if ($script_enable==1){
	print "<img src=\"./logo.png\" alt=\"Logo\" width=\"64\" height=\"64\">";
	print "<font color=\"green\"><h3>Script Status: Active</h3></font>";
}else{
	print "<img src=\"./logo.png\" alt=\"Logo\" width=\"64\" height=\"64\">";
	print "<font color=\"red\"><h3>Script Status: Inactive</h3></font>";
}
```
which results in: 
![image](https://github.com/user-attachments/assets/aa3b2da7-cc5b-4f74-95f3-c6450a6d3b37)

Maybe with your html skills you can fix the code?

**Comment by wallacebrf** [comment]
Yes I can do that. I was also already toying with the idea to add color elsewhere 

I was planning to add color of testing is active, adding color to if the smart is disabled etc.

**Comment by 007revad** [comment]
I notice the webui is sourcing the logo from github. I would change it to cope with the NAS maybe having no internet access.

To only source the logo.png file from github if logo.png is not in the same folder as the php file I would have done something like add the following near the top of the php file:
```
if (file_exists("./logo.png")) {
	$logo = "./logo.png";
} else {
	$logo = "https://raw.githubusercontent.com/wallacebrf/Synology-SMART-test-scheduler/refs/heads/main/images/logo.png";
}
```

Then replace this:
```
<td><img src=\"https://raw.githubusercontent.com/wallacebrf/Synology-SMART-test-scheduler/refs/heads/main/images/logo.png\" alt=\"Logo\" width=\"64\" height=\"64\"></td>
```

with:
```
<td><img src=\"$logo\" alt=\"Logo\" width=\"64\" height=\"64\"></td>
```

**Comment by wallacebrf** [comment]
i will update that tomorrow
