### ISSUE TITLE
Win10 File Explorer sees my "smart" web portal as a device

### ISSUE THREAD

**Issue by 007revad** [wallacebrf/Synology-SMART-test-scheduler#33]
Is it normal for Web Portal's hostnames to appear on the LAN as network devices?

![image](https://github.com/user-attachments/assets/5505b6dc-dd2d-4e8c-85d3-f33949373eb1)

![image](https://github.com/user-attachments/assets/4e03cf37-a0ba-42df-b73f-5e0082b0142c)

![image](https://github.com/user-attachments/assets/2091a070-541b-4398-bc68-98b325d66582)

**Comment by wallacebrf** [comment]
i was not aware of this as i have network discovery turned off on all of my networked devices. "slightly" increases security when things are not advertising their existence.
